In [1]:
import numpy as np
import sys, os
sys.path.append(os.pardir + '/deep-learning-from-scratch/') 
from common.functions import softmax, cross_entropy_error
from common.gradient import numerical_gradient

In [4]:
class simpleNet:
    def __init__(self):
        # 正規分布から、2×3の乱数行列を作成
        self.W = np.random.randn(2, 3)
    
    def predict(self, x):
        return np.dot(x, self.W)
    
    def loss(self, x, t):
        z = self.predict(x)
        y = softmax(z)
        return cross_entropy_error(y, t)    

In [5]:
net = simpleNet()

In [6]:
print(net.W)

[[-0.39024831  0.84359212 -0.17331183]
 [-0.6712391  -1.16544074 -1.23187398]]


In [8]:
x = np.array([0.6, 0.9])
pred = net.predict(x)
pred

array([-0.83826418, -0.54274139, -1.21267368])

In [9]:
np.argmax(pred)

1

In [10]:
t = np.array([0, 0, 1])
net.loss(x, t)

1.4834745078609337

In [11]:
def f(W):
    return net.loss(x, t)

dW = numerical_gradient(f, net.W)
dW

array([[ 0.19792017,  0.26597081, -0.46389098],
       [ 0.29688025,  0.39895621, -0.69583646]])